"""Stage 4 Phase 3: Zero-Short rebuild — reconstruct the candidate set in an EMPTY temp
directory INSIDE AgentAssets, strictly from migration-manifest.json sources, then re-run every
hard validation there. Never touches the formal repos or the real candidate roots.

Run: python -B tools/stage4_zero_short.py <staging_root> <project_root>
Temp dir: <staging>/06_评测与校验/evidence/stage-4/zero-short-tmp  (deletable by rule below)
Cleanup rule: removed in a finally block; leftover removal = delete that one directory.
"""
from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
ROOT = Path(sys.argv[1]).resolve()
PROJECT = Path(sys.argv[2]).resolve()
MANIFEST = json.loads((ROOT / "07_迁移包" / "migration-manifest.json").read_text(encoding="utf-8"))
TMP = ROOT / "06_评测与校验" / "evidence" / "stage-4" / "zero-short-tmp"
PY = sys.executable
failures: list[str] = []


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main() -> int:
    if TMP.exists():
        shutil.rmtree(TMP)  # idempotent rebuild rule
    (TMP / "04_知识库候选").mkdir(parents=True)
    (TMP / "05_模板库候选" / "research-rejected").mkdir(parents=True)

    # 1) rebuild per manifest sources + governance companions needed by the validators
    ops = [o for o in MANIFEST["operations"] if o["op"] == "create"]
    for op in ops:
        src = ROOT / op["source"]
        dst = TMP / op["source"]
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
    for companion in ("04_知识库候选/knowledge-manifest.jsonl",
                      "04_知识库候选/knowledge-coverage-matrix.csv",
                      "05_模板库候选/research-rejected/sdxl-finetune-conservative.toml",
                      "05_模板库候选/research-rejected/sdxl-lora-oft-conservative.toml"):
        if not (ROOT / companion).exists():
            failures.append(f"missing governance companion in source: {companion}")
        else:
            shutil.copy2(ROOT / companion, TMP / companion)

    # 2) hash parity vs manifest
    for op in ops:
        if sha256(TMP / op["source"]) != op["sha256"]:
            failures.append(f"hash mismatch on rebuild: {op['source']}")

    # 3) input-purity check BEFORE gate re-runs (validator artifacts generated by the
    #    re-runs below are outputs, not rebuild inputs, and must not count here)
    allowed_inputs = {op["source"] for op in ops} | {
        "04_知识库候选/knowledge-manifest.jsonl",
        "04_知识库候选/knowledge-coverage-matrix.csv",
        "05_模板库候选/research-rejected/sdxl-finetune-conservative.toml"}
    allowed_inputs.add("05_模板库候选/research-rejected/sdxl-lora-oft-conservative.toml")
    extra = [str(p.relative_to(TMP)).replace("\\", "/") for p in TMP.rglob("*") if p.is_file()
             and str(p.relative_to(TMP)).replace("\\", "/") not in allowed_inputs]
    if extra:
        failures.append(f"unexpected input files in rebuilt root: {extra[:5]}")

    # 4) hard gates re-run against the rebuilt root
    for label, cmd in [
        ("lint", [PY, "-B", str(ROOT / "tools/stage2_lint.py"), str(TMP)]),
        ("templates", [str(PROJECT / ".venv-dev/Scripts/python.exe"), "-B",
                       str(ROOT / "tools/stage3_validate_templates.py"), str(TMP), str(PROJECT)]),
    ]:
        p = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", errors="replace")
        if p.returncode != 0:
            failures.append(f"{label} on rebuilt root exit {p.returncode}: {(p.stdout or p.stderr)[-400:]}")

    report = {"rebuilt_files": len(ops), "hash_parity": not any("hash" in f for f in failures),
              "gates": "lint+templates re-run on temp root", "unexpected_files": extra,
              "failures": failures, "result": "pass" if not failures else "fail"}
    out = ROOT / "06_评测与校验" / "evidence" / "stage-4" / "phase-3"
    out.mkdir(parents=True, exist_ok=True)
    (out / "zero-short-report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 1 if failures else 0


try:
    rc = main()
finally:
    if TMP.exists():
        shutil.rmtree(TMP, ignore_errors=True)
raise SystemExit(rc)
